project:
  type: website

website:
  title: "Grasshoppermouse"
  site-url: https://blog.edhagen.net
  twitter-card: true
  open-graph: true
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/ed_hagen
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

